package model.dal.entity;
// Generated Mar 26, 2019, 6:28:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name="coupon"
    ,catalog="ecommerce"
)
public class Coupon  implements java.io.Serializable {


     private int cid;
     private String cdiscount;
     private Set<User> users = new HashSet<User>(0);

    public Coupon() {
    }

	
    public Coupon(int cid) {
        this.cid = cid;
    }
    public Coupon(int cid, String cdiscount, Set<User> users) {
       this.cid = cid;
       this.cdiscount = cdiscount;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="cid", unique=true, nullable=false)
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }

    
    @Column(name="cdiscount")
    public String getCdiscount() {
        return this.cdiscount;
    }
    
    public void setCdiscount(String cdiscount) {
        this.cdiscount = cdiscount;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_has_coupon", catalog="ecommerce", joinColumns = { 
        @JoinColumn(name="couponID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="userID", nullable=false, updatable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


