package model.dal.entity;
// Generated Mar 26, 2019, 6:28:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProductDetails generated by hbm2java
 */
@Entity
@Table(name="product_details"
    ,catalog="ecommerce"
)
public class ProductDetails  implements java.io.Serializable {


     private int productId;
     private Product product;
     private String productImage;
     private String productColor;

    public ProductDetails() {
    }

	
    public ProductDetails(Product product) {
        this.product = product;
    }
    public ProductDetails(Product product, String productImage, String productColor) {
       this.product = product;
       this.productImage = productImage;
       this.productColor = productColor;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="product"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="productID", unique=true, nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="productImage")
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    
    @Column(name="productColor")
    public String getProductColor() {
        return this.productColor;
    }
    
    public void setProductColor(String productColor) {
        this.productColor = productColor;
    }




}


